### ISSUE TITLE
Scoped CSS does not work when element is added from JavaScript DOM

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell-renderer#30]
This code below will not change the color of inner-element to red.
```html
<AbellComponent>
<template>
  <div id="hello"></div>
</template>
<style>
  .inner-element {
    background-color: #f30;
  }
</style>
<script>
  document.querySelector('#hello').innerHTML = `
    <div class="inner-element">I am added from JS</div>
  `
</script>
</AbellComponent>
```

Currently, we add `data-abell-<hash>` attribute to all the elements inside template tag. The elements added from DOM do not get these attributes and hence ignored by styles.

Not really sure how we can solve this issue just leaving it here for future reference.

**Comment by pantharshit00** [comment]
Linking discord discussion: https://discordapp.com/channels/706385518539309096/706385701108711503/760939334357614592

**Comment by saurabhdaware** [comment]
Yup this seems like a expected thing + now we can have multiple scripts and styles so we can have global styles for particular part.
