### ISSUE TITLE
Recursively build abell files

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell-renderer#6]
Currently, abell-renderer CLI only supports building one file,
```sh
abell-renderer --input src/index.abell --output dist/index.html
```

It would be very helpful if we can build every .abell file when folder is provided
```sh
abell-renderer --input src --output dist
```

*Note: Since abell-renderer is low-level API we will have to do this without adding any additional dependencies unless there's no other way to do it.*

**Files to change:**
[src/bin.js](https://github.com/abelljs/abell-renderer/blob/master/src/bin.js) includes all the code that is executed when CLI is called

**Comment by Pika1998** [comment]
Hey i would like to work on this

**Comment by saurabhdaware** [comment]
cool cool! go ahead @Pika1998

**Comment by Pika1998** [comment]
Close this issue :)
